project_id = "xtdukbzdbzbemyqaifhp"
[storage]
enabled = true

[[publications]]
name = "public"
allowed_roles = ["authenticated", "service_role"]
tables = ["profiles"]

[[storage.buckets]]
name = "avatars"
public = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://poultry-pulse-india.vercel.app"]
